
[TitaniumConfig]
	#A Boolean that is true by default
	thisIsABoolean = true
<<<<<<< Updated upstream
	#A Boolean that is false by default
	NOT_BOOLEAN = false
	intAngery = 7
=======
	intAngery = 7
	#A Boolean that is false by default
	NOT_BOOLEAN = false
>>>>>>> Stashed changes

	[TitaniumConfig.Dabber]
		dabby = "lil dab"

	[TitaniumConfig.TestBlock]
		DUMB_VALUE = 135

